/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabe e Koto
 */
public class TelaClientes extends javax.swing.JFrame {

    /**
     * Creates new form TelaClientes
     */
    public TelaClientes() {
        initComponents();
    }
    
    public TelaClientes(String cargo) {
        initComponents();
        if (cargo.equalsIgnoreCase("Estagiário")){
            btnSalvar.setEnabled(false);
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else if (cargo.equalsIgnoreCase("Vendedor")){
            btnLimpar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        lblBairro = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblEndereco = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        lblCidade = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controle de Clientes");
        getContentPane().setLayout(null);

        lblNome.setText("Nome");
        getContentPane().add(lblNome);
        lblNome.setBounds(30, 90, 34, 14);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(140, 180, 240, 30);

        lblBairro.setText("Bairro:");
        getContentPane().add(lblBairro);
        lblBairro.setBounds(30, 190, 70, 14);
        getContentPane().add(txtNome);
        txtNome.setBounds(140, 80, 330, 30);

        lblCPF.setText("CPF:");
        getContentPane().add(lblCPF);
        lblCPF.setBounds(30, 40, 34, 14);
        getContentPane().add(txtCpf);
        txtCpf.setBounds(140, 30, 180, 30);

        lblEndereco.setText("Endereço:");
        getContentPane().add(lblEndereco);
        lblEndereco.setBounds(30, 140, 60, 14);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(140, 130, 330, 30);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(140, 230, 240, 30);

        lblCidade.setText("Cidade");
        getContentPane().add(lblCidade);
        lblCidade.setBounds(30, 240, 60, 14);
        getContentPane().add(txtTelefone);
        txtTelefone.setBounds(140, 280, 190, 30);

        lblTelefone.setText("Telefone");
        getContentPane().add(lblTelefone);
        lblTelefone.setBounds(30, 290, 50, 14);

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar);
        btnLimpar.setBounds(530, 330, 90, 40);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(40, 330, 90, 40);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar);
        btnConsultar.setBounds(170, 330, 90, 40);

        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir);
        btnExcluir.setBounds(290, 330, 90, 40);

        jButton5.setText("Salvar");
        getContentPane().add(jButton5);
        jButton5.setBounds(290, 330, 90, 40);

        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar);
        btnAlterar.setBounds(410, 330, 90, 40);

        setSize(new java.awt.Dimension(679, 442));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
        //Declaração das variáveis
            Connection con;
            PreparedStatement st;
            //Carregamento do Driver da biblioteca
            Class.forName("com.mysql.jdbc.Driver");
            //Estabelecimento da conexão com o Banco de dados
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/usuarios","root","nagito");
            // Criação do comando SQL que vai ser executado nno Banco de dados
           
             st = con.prepareStatement("INSERT INTO cliente values (?,?,?,?,?,?)");
               st.setString(1,txtCpf.getText());
               st.setString(2,txtNome.getText());
               st.setString(3,txtEndereco.getText());
               st.setString(4,txtBairro.getText());
               st.setString(5,txtCidade.getText());
               st.setString(6,txtTelefone.getText());
               //Execução do comando SQL
               st.executeUpdate();
               //Mensagens para o usuário do software 
                JOptionPane.showMessageDialog(null,"Cliente cadastrado com sucesso");
                Limpar();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Você não tem o driver de conexão na biblioteca");
        }  catch (SQLException ex) {
            if(ex.getErrorCode()==1062){
               JOptionPane.showMessageDialog(null,"Este CPF já está cadastrado em nosso sistema");
               Limpar();
            } else {
               JOptionPane.showMessageDialog(null,"Erro ao tentar salvar os dados\nEntre em contato  com o administrador do sistema");
            }
        }    
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
                Limpar();
    }//GEN-LAST:event_btnLimparActionPerformed

 private void Limpar(){
    txtBairro.setText("");
    txtCidade.setText("");
    txtCpf.setText("");
    txtEndereco.setText("");
    txtNome.setText("");
    txtTelefone.setText("");    
    txtCpf.requestFocus();
    btnExcluir.setEnabled(false);
    
}
    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        try {
            Connection con;
            PreparedStatement st;
            ResultSet rs;
            //Carregamento do Driver da biblioteca
            Class.forName("com.mysql.jdbc.Driver");
            //Estabelecimento da conexão com o Banco de dados
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/usuarios","root","nagito");          
            // Criação do comando SQL que vai ser executado nno Banco de dados
            st = con.prepareStatement("SELECT * FROM CLIENTE WHERE CPF = ?");
            st.setString(1, txtCpf.getText());
            rs = st.executeQuery();
            if(rs.next()){ //se encontrou o usuário
                txtNome.setText(rs.getNString("nome"));
                txtEndereco.setText(rs.getNString("endereco"));
                txtBairro.setText(rs.getNString("bairro"));
                txtCidade.setText(rs.getNString("cidade"));
                txtTelefone.setText(rs.getNString("telefone"));
                btnExcluir.setEnabled(true);
                btnAlterar.setEnabled(true);
                txtCpf.setEditable(false);
            } else {
                JOptionPane.showMessageDialog(null, "CPF do cliente não encontrado");
                Limpar();
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Driver de conexão não encontrado" + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro na consulta ao Banco de dados" + ex.getMessage());  
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
        //Declaração das variáveis
            Connection con;
            PreparedStatement st;
            //Carregamento do Driver da biblioteca
            Class.forName("com.mysql.jdbc.Driver");
            //Estabelecimento da conexão com o Banco de dados
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/usuarios","root","nagito");
            // Criação do comando SQL que vai ser executado nno Banco de dados
           
             st = con.prepareStatement("DELETE FROM cliente WHERE CPF = ?");
               st.setString(1,txtCpf.getText());
               txtCpf.setEditable(true);
               //Execução do comando SQL
               st.executeUpdate();
               //Mensagens para o usuário do software 
                JOptionPane.showMessageDialog(null,"Cliente excluido com sucesso");
                Limpar();
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Você não tem o driver de conexão na biblioteca");
        }  catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar excluir o cliente.Entre em contato com o administrador do sistema e innforme o erro " + ex.getMessage());
         }    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
          try {
            //Declaração das variáveis
            Connection con;
            PreparedStatement st;
            //Carregamento do Driver da biblioteca
            Class.forName("com.mysql.jdbc.Driver");
            //Estabelecimento da conexão com o Banco de dados

            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/usuarios","root","nagito");          
            // Criação do comando SQL que vai ser executado nno Banco de dados
              st = con.prepareStatement("UPDATE cliente SET nome = ?, endereco = ?, bairro = ?, cidade = ?, telefone = ? WHERE cpf = ?");
            st.setString(1, txtNome.getText());
            st.setString(2, txtEndereco.getText());
            st.setString(3, txtBairro.getText());
            st.setString(4, txtCidade.getText());
            st.setString(5, txtTelefone.getText());            
            st.setString(6, txtCpf.getText());
            
            //Execução do comando SQL
            st.executeUpdate();
            //Mensagens para o usuário do software 
            JOptionPane.showMessageDialog(null, "Cliente alterado com sucesso");
            Limpar();
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            txtCpf.setEditable(true);
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Você não tem o driver de conexão na biblioteca " + ex.getMessage());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao tentar excluir o cliente. Entre em contato com o administrador do sistema e informe o erro " + ex.getMessage());
        }       

    }//GEN-LAST:event_btnAlterarActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaClientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblEndereco;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
