/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Gabe e Koto
 */
public class TelaMenu extends javax.swing.JFrame {
    private String cargo;
    /**
     * Creates new form TelaMenu
     * @param nome
     */
    public TelaMenu(String nome, String cargo) {
        this.cargo = cargo;
        initComponents();
        lblSaudacao.setText("Bem-vindo " + nome);
         if (cargo.equalsIgnoreCase("Estagiário")){
            btnNotaFiscal.setEnabled(false);
            btnFuncionarios.setEnabled(false);
        } else if (cargo.equalsIgnoreCase("Vendedor")){
            btnFuncionarios.setEnabled(false);
        } else if (cargo.equalsIgnoreCase("Analista")){
            btnNotaFiscal.setEnabled(false);
            btnFuncionarios.setEnabled(false);
            btnProdutos.setEnabled(false);            
        }
    }
    public TelaMenu() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSaudacao = new javax.swing.JLabel();
        btnFuncionarios = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnNotaFiscal = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();

        setTitle("MenuPrincipal");
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        lblSaudacao.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 12)); // NOI18N
        lblSaudacao.setOpaque(true);
        getContentPane().add(lblSaudacao);
        lblSaudacao.setBounds(300, 200, 170, 40);

        btnFuncionarios.setText("Controle de Funcionários");
        getContentPane().add(btnFuncionarios);
        btnFuncionarios.setBounds(260, 30, 210, 70);

        btnProdutos.setText("Controle de Produtos");
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        getContentPane().add(btnProdutos);
        btnProdutos.setBounds(260, 110, 210, 70);

        btnNotaFiscal.setText("Emissão de Nota Fiscal");
        getContentPane().add(btnNotaFiscal);
        btnNotaFiscal.setBounds(20, 110, 210, 70);

        btnClientes.setText("Controle de Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnClientes);
        btnClientes.setBounds(20, 30, 210, 70);

        setSize(new java.awt.Dimension(535, 301));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
                TelaClientes c;
                c = new TelaClientes(cargo);
                c.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
                TelaProdutos p;
                p = new TelaProdutos();
                p.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_btnProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnFuncionarios;
    private javax.swing.JButton btnNotaFiscal;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JLabel lblSaudacao;
    // End of variables declaration//GEN-END:variables
}
